Thesis/Thesis/urls.py
from django.contrib import admin
from django.urls import path, include
from content.views import index_page

urlpatterns = [
    path('', index_page),
    path('admin/', admin.site.urls),
    path('thesis/', include('content.urls', namespace = 'content')),
]

Thesis/content/urls.py
from django.urls import path
from . import views

app_name = "content"

urlpatterns = [
    path('', views.show_thesis, name='thesis_list'),
    path('search/', views.thesis_search, name='thesis_search'),
    path('<int:year>/<int:month>/<int:day>/<slug:thesis>/',views.thesis_details,name = "thesis_details"),
    path("<int:thesis_id>/comment/", views.post_comment, name = 'post_comment'),
]

Thesis/content/models.py
from django.db import models
from django.utils.text import slugify
from django.utils import timezone
from django.urls import reverse

class Thesis(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True, blank=True
                            ,unique_for_date = "published_date")  
    authors = models.CharField(max_length=100)
    abstract = models.TextField()
    body = models.TextField()
    panelist = models.CharField(max_length=100)
    advisors = models.CharField(max_length=255)
    department = models.CharField(max_length=100)  
    defense_date = models.DateField()
    published_date = models.DateField(default=timezone.now)
    keywords = models.CharField(max_length=255)
    status = models.CharField(
        max_length=2,
        choices=[
            ("RJ", "Rejected"),
            ("PB", "Published"),
            ("UR", "Under Review"),
        ],
        default="UR"
    )

    class Meta:
        ordering = ['-published_date']
        indexes = [
            models.Index(fields=['-published_date'])
        ]

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('content:thesis_details', args=[self.published_date.year, self.published_date.month,self.published_date.day,self.slug])
        

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)  
        super().save(*args, **kwargs)

class Comment(models.Model):
    post = models.ForeignKey(Thesis,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email=models.EmailField()
    body=models.TextField()
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    active=models.BooleanField(default=True)

    class Meta:
        ordering =['created']
        indexes = [
            models.Index(fields=['created'])
        ]

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

Thesis/content/forms.py
from .models import Comment
from django.forms import ModelForm

class CommentForm(ModelForm):
    class Meta:
        model = Comment 
        fields = ['name','email','body']

Thesis/content/views.py
from django.shortcuts import render, get_object_or_404
from .models import Thesis, Comment
from django.core.paginator import Paginator
from .forms import CommentForm
from django.views.decorators.http import require_POST



def index_page(request):
    return render(request, 'landing_page.html')

def show_thesis(request):
    theses_list = Thesis.objects.all()
    paginator = Paginator(theses_list, 3)
    page_number = request.GET.get('page', 1)
    theses = paginator.page(page_number)
    return render(request, 'inner_working/list.html', {'existing_data': theses})


def thesis_search(request):
    query = request.GET.get('q')
    theses = Thesis.objects.all()
    
    if query:
        print("Query:", query)
        theses = theses.filter(keywords__icontains=query)

    return render(request, 'inner_working/list.html', {'theses': theses, 'search_query': query})

def thesis_details(request, year, month, day, thesis):
    thesis = get_object_or_404(Thesis,slug=thesis,published_date__year = year, published_date__month = month, published_date__day = day)
    comments = thesis.comments.filter(active=True)
    form = CommentForm()
    return render(request,"inner_working/thesis_details.html", {"thesis":thesis,'comments':comments, 'form':form})


@require_POST
def post_comment(request, thesis_id):
    post = get_object_or_404(Thesis,id=thesis_id)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    
    return render(request, 'inner_working/comment.html', {'post':post, 'form':form, 'comment':comment })

Thesis/content/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%}{%endblock%}</title>
    <link rel="stylesheet" href="{% static 'css/style_details.css' %}">
</head>
<body>
    {% block content %}
        
    {% endblock content %}
</body>
</html>

Thesis/content/templates/inner_working/comment.html
{% extends "base.html"%}

{% block title%} Add a comment{%endblock%}

{%block content%}
    {%if comment%}
        <h2>Your Comment has been added.</h2>
        <p><a href="{{ comment.post.get_absolute_url }}">Back to the post</a></p>
    {%else%}
        {%include 'inner_working/comment_form.html'%}
    {%endif%}

{%endblock%}

Thesis/content/templates/inner_working/comment_form.html
<h2>Add a new comment</h2>
<form action="{%url 'content:post_comment' thesis.id%}" method="post">
    {{form.as_p}}
    {%csrf_token%}
    <p><input type="submit" name="add comment" id=""></p>
</form>

Thesis/content/templates/inner_working/list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Thesis List</title>
    <link rel="stylesheet" href="{% static 'css/style_base.css' %}">
</head>
<body>
    <div class="head_style">
        <h1>Thesis List</h1>
        <div class="search-container">
            <form action="{% url 'content:thesis_search' %}" method="get" onsubmit="return validateSearch()">
                <input type="text" name="q" placeholder="Search Keywords" value="{{ request.GET.q }}">
                <button type="submit">Search</button>
            </form>
        </div>
    </div>

    <!-- Display Existing Data -->
    {% if not request.GET.q and existing_data %}
    <div class="existing-data">
        <h2>Thesis List</h2>
        {% for thesis in existing_data %}
            <div class="thesis-item">
                <h2><a href="{{thesis.get_absolute_url}}">{{ thesis.title }}</a></h2>
                <p>Abstract: {{thesis.abstract }}</p>
                <p>Published: {{ thesis.published_date }}</p>
                <p>Keywords: {{ thesis.keywords }}</p>
            </div>
        {% endfor %}
        {% include "paginator.html" with page=theses%}
    </div>
    {% endif %}

    <!-- Search  -->
    {% if search_query %}
    <div class="search-results">
        <h2>Search Results for "{{ search_query }}"</h2>
        {% if theses %}
            {% for thesis in theses %}
                <div class="thesis-item">
                    <h2><a href="{{thesis.get_absolute_url}}">{{ thesis.title }}</a></h2>
                    <p>Published: {{ thesis.published_date }}</p>
                    <p>Keywords: {{ thesis.keywords }}</p>
                </div>
            {% endfor %}
        {% else %}
            <p>No results found.</p>
        {% endif %}
    </div>
    {% endif %}
</body>
</html>

Thesis/content/templates/inner_working/thesis_details.html
{% extends 'base.html' %}

{% block title %}{{ thesis.title }} - Thesis Detail{% endblock %}

{% block content %}
<div class="thesis-detail">
    <h1 class="thesis-title">{{ thesis.title }}</h1>
    <div class="thesis-info">
        <p class="author"><strong>Authors:</strong> {{ thesis.authors }}</p>
        <p class="abstract"><strong>Abstract:</strong> {{ thesis.abstract }}</p>
        <p class="body"><strong>body:</strong> {{ thesis.body }}</p>
        <p class="panelist"><strong>Panelist:</strong> {{ thesis.panelist }}</p>
        <p class="advisor"><strong>Advisors:</strong> {{ thesis.advisors }}</p>
        <p class="defense-date"><strong>Defense Date:</strong> {{ thesis.defense_date }}</p>
        <p class="published-date"><strong>Published Date:</strong> {{ thesis.published_date }}</p>
        <p class="keywords"><strong>Keywords:</strong> {{ thesis.keywords }}</p>
        <p class="status"><strong>Status:</strong> {{ thesis.get_status_display }}</p>
    </div>
</div>

<div class="comment-section">
    <h2 class="comment-heading">Comments</h2>
    <div class="comments">
        {% with comments.count as total_comments%}
            <h2> {{total_comments}} Comment{{total_comments|pluralize}}</h2>
        {%endwith%}
        {%for comment in comments%}
            <div class="comment_sec">
                <p class="info">
                    Comment {{forloop.counter}} by {{comment.name}}
                    {{comment.created}}
                </p>
                {{comment.body|linebreaks}}
            </div>
            {%empty%}
                <p>There are no comments.</p>
        {%endfor%}

        {%include "inner_working/comment_form.html"%}
    </div>
</div>

<div class="return">
    <a href="/thesis">Return to Thesis List</a>
</div>
{% endblock %}

Thesis/content/templates/landing_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Landing Page</title>
</head>
<body>
    <h1>Thesis Blog</h1>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. 
        Odit dolorum sit at ex reiciendis quod excepturi alias id quos placeat libero esse veritatis eligendi repellendus quae nostrum, aliquid explicabo nisi!</p>
    <button onclick="window.location.href='/thesis/'">View Thesis List</button>
</body>
</html>

Thesis/content/templates/list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Thesis List</title>
    <link rel="stylesheet" href="{% static 'css/style_base.css' %}">
</head>
<body>
    <div class="head_style">
        <h1>Thesis List</h1>
        <div class="search-container">
            <form action="{% url 'thesis_search' %}" method="get" onsubmit="return validateSearch()">
                <input type="text" name="q" placeholder="Search Keywords" value="{{ request.GET.q }}">
                <button type="submit">Search</button>
            </form>
        </div>
    </div>

    <!-- Display Existing Data -->
    {% if not request.GET.q and existing_data %}
    <div class="existing-data">
        <h2>Thesis List</h2>
        {% for thesis in existing_data %}
            <div class="thesis-item">
                <h2><a href="{%url 'thesis_details' thesis.id%}">{{ thesis.title }}</a></h2>
                <p>Published: {{ thesis.published_date }}</p>
                <p>Keywords: {{ thesis.keywords }}</p>
            </div>
        {% endfor %}
    </div>
    {% endif %}

    <!-- Search  -->
    {% if search_query %}
    <div class="search-results">
        <h2>Search Results for "{{ search_query }}"</h2>
        {% if theses %}
            {% for thesis in theses %}
                <div class="thesis-item">
                    <h2>{{ thesis.title }}</h2>
                    <p>Published: {{ thesis.published_date }}</p>
                    <p>Keywords: {{ thesis.keywords }}</p>
                </div>
            {% endfor %}
        {% else %}
            <p>No results found.</p>
        {% endif %}
    </div>
    {% endif %}
</body>
</html>

Thesis/content/templates/paginator.html
<div class="pagination">
    <span class="step-links">
        {% if existing_data.has_previous %}
            <a href="?page {{existing_data.previous_page_number}}">Previous</a>
        {%endif%}
        <span class="current">
            Page {{existing_data.number}} of {{existing_data.paginator.num_pages}}
        </span>
        {%if existing_data.has_next%}
        <a href="?page={{existing_data.next_page_number}}">Next</a>
        {% endif %}
    </span>
</div>